/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/*
 * main.c
 *
 * Descripcion: Pruebas de tipos de datos, sistemas numericos y desplazamientos - Semana 1.
 * Autor: Jimmy Stebym Rosero Barrera (jiroserob@unal.edu.co)
 *
 */

#include <stdint.h> /* Tipos de ancho fijo obligatorios */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

/* Seccion 3: Variables Globales */
uint8_t variable_8bits = 0;
uint16_t variable_16bits = 0;
uint32_t variable_32bits = 0;

uint16_t variable_16bits_dec = 0;
uint16_t variable_16bits_bin = 0;
uint16_t variable_16bits_hex = 0; /* Nombre corregido para coincidir con el uso */

int main(void)
{
	/* Asignaciones basicas */
	variable_8bits = 123;
	variable_16bits = 4986;
	variable_32bits = 12345678;

	/* Pruebas de sistemas numericos */
	variable_16bits_dec = 32;       /* Decimal */
	variable_16bits_bin = 0b100000; /* Binario (usa prefijo 0b) */
	variable_16bits_hex = 0x20;     /* Hexadecimal (usa prefijo 0x) */

	/* Operaciones de desplazamiento */
	variable_16bits_hex = variable_16bits_hex << 3; /* Multiplica por 2^3 (8) */
	variable_16bits_hex = variable_16bits_hex >> 3; /* Divide por 2^3 (8) */

    while(1) /* Bucle infinito obligatorio */
    {
    	/* El codigo se queda aqui tras ejecutar las pruebas iniciales */
    }
}
