/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body - Semaforo FSM integrado
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f4xx.h"

// --- VARIABLES GLOBALES ---
uint8_t estado_semaforo = 0;   // 0=VERDE, 1=AMARILLO, 2=ROJO
uint32_t contador_tiempo = 0;

int main(void)
{
    // --- 5. CONFIGURACIÓN DE PERIFÉRICOS (GPIO) ---
    // 1. Habilitar reloj para GPIOA
    RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;

    // 2. Configurar Pines PA5, PA6, PA7 como SALIDAS
    // Limpiamos los bits de configuración (MODER)
    GPIOA->MODER &= ~(GPIO_MODER_MODER5 | GPIO_MODER_MODER6 | GPIO_MODER_MODER7);
    // Asignamos modo salida (01)
    GPIOA->MODER |= (GPIO_MODER_MODER5_0 | GPIO_MODER_MODER6_0 | GPIO_MODER_MODER7_0);

    // --- 7. BUCLE INFINITO (Lógica del Semáforo) ---
    while(1)
    {
        contador_tiempo++;

        // Apagamos todo antes de decidir qué encender
        GPIOA->ODR &= ~(GPIO_ODR_ODR_5 | GPIO_ODR_ODR_6 | GPIO_ODR_ODR_7);

        // FSM: Según el estado, encendemos el LED correspondiente
        if (estado_semaforo == 0) {
            GPIOA->ODR |= GPIO_ODR_ODR_5; // VERDE
        }
        else if (estado_semaforo == 1) {
            GPIOA->ODR |= GPIO_ODR_ODR_6; // AMARILLO
        }
        else if (estado_semaforo == 2) {
            GPIOA->ODR |= GPIO_ODR_ODR_7; // ROJO
        }

        // Cambio de estado
        if (contador_tiempo > 2000000) {
            estado_semaforo++;
            if (estado_semaforo > 2) estado_semaforo = 0;
            contador_tiempo = 0;
        }
    }
}
